// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONNECTROOMREQUEST_RS_HIGH_LIFE_FBS_H_
#define FLATBUFFERS_GENERATED_CONNECTROOMREQUEST_RS_HIGH_LIFE_FBS_H_

#include "flatbuffers/flatbuffers.h"

namespace rs {
namespace high {
namespace life {
namespace fbs {

struct ConnectRoomRequest;

struct ConnectRoomRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ROOMID = 4,
    VT_USERID = 6,
    VT_USERNAME = 8
  };
  const flatbuffers::String *roomId() const {
    return GetPointer<const flatbuffers::String *>(VT_ROOMID);
  }
  const flatbuffers::String *userId() const {
    return GetPointer<const flatbuffers::String *>(VT_USERID);
  }
  const flatbuffers::String *username() const {
    return GetPointer<const flatbuffers::String *>(VT_USERNAME);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ROOMID) &&
           verifier.Verify(roomId()) &&
           VerifyOffsetRequired(verifier, VT_USERID) &&
           verifier.Verify(userId()) &&
           VerifyOffsetRequired(verifier, VT_USERNAME) &&
           verifier.Verify(username()) &&
           verifier.EndTable();
  }
};

struct ConnectRoomRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_roomId(flatbuffers::Offset<flatbuffers::String> roomId) {
    fbb_.AddOffset(ConnectRoomRequest::VT_ROOMID, roomId);
  }
  void add_userId(flatbuffers::Offset<flatbuffers::String> userId) {
    fbb_.AddOffset(ConnectRoomRequest::VT_USERID, userId);
  }
  void add_username(flatbuffers::Offset<flatbuffers::String> username) {
    fbb_.AddOffset(ConnectRoomRequest::VT_USERNAME, username);
  }
  ConnectRoomRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ConnectRoomRequestBuilder &operator=(const ConnectRoomRequestBuilder &);
  flatbuffers::Offset<ConnectRoomRequest> Finish() {
    const auto end = fbb_.EndTable(start_, 3);
    auto o = flatbuffers::Offset<ConnectRoomRequest>(end);
    fbb_.Required(o, ConnectRoomRequest::VT_ROOMID);
    fbb_.Required(o, ConnectRoomRequest::VT_USERID);
    fbb_.Required(o, ConnectRoomRequest::VT_USERNAME);
    return o;
  }
};

inline flatbuffers::Offset<ConnectRoomRequest> CreateConnectRoomRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> roomId = 0,
    flatbuffers::Offset<flatbuffers::String> userId = 0,
    flatbuffers::Offset<flatbuffers::String> username = 0) {
  ConnectRoomRequestBuilder builder_(_fbb);
  builder_.add_username(username);
  builder_.add_userId(userId);
  builder_.add_roomId(roomId);
  return builder_.Finish();
}

inline flatbuffers::Offset<ConnectRoomRequest> CreateConnectRoomRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *roomId = nullptr,
    const char *userId = nullptr,
    const char *username = nullptr) {
  return rs::high::life::fbs::CreateConnectRoomRequest(
      _fbb,
      roomId ? _fbb.CreateString(roomId) : 0,
      userId ? _fbb.CreateString(userId) : 0,
      username ? _fbb.CreateString(username) : 0);
}

inline const rs::high::life::fbs::ConnectRoomRequest *GetConnectRoomRequest(const void *buf) {
  return flatbuffers::GetRoot<rs::high::life::fbs::ConnectRoomRequest>(buf);
}

inline bool VerifyConnectRoomRequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<rs::high::life::fbs::ConnectRoomRequest>(nullptr);
}

inline void FinishConnectRoomRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<rs::high::life::fbs::ConnectRoomRequest> root) {
  fbb.Finish(root);
}

}  // namespace fbs
}  // namespace life
}  // namespace high
}  // namespace rs

#endif  // FLATBUFFERS_GENERATED_CONNECTROOMREQUEST_RS_HIGH_LIFE_FBS_H_
