// automatically generated by the FlatBuffers compiler, do not modify

package rs.high.life.fbs;

public final class AnyClientContent {
  private AnyClientContent() { }
  public static final byte NONE = 0;
  public static final byte ConnectRoomRequest = 1;
  public static final byte VWChatEvent = 2;

  public static final String[] names = { "NONE", "ConnectRoomRequest", "VWChatEvent", };

  public static String name(int e) { return names[e]; }
}

