// automatically generated by the FlatBuffers compiler, do not modify

package rs.high.life.fbs;

public final class AnyServerContent {
  private AnyServerContent() { }
  public static final byte NONE = 0;
  public static final byte ConnectRoomResponse = 1;
  public static final byte AvatarJoinedEvent = 2;
  public static final byte AvatarLeftEvent = 3;
  public static final byte VWChatEvent = 4;

  public static final String[] names = { "NONE", "ConnectRoomResponse", "AvatarJoinedEvent", "AvatarLeftEvent", "VWChatEvent", };

  public static String name(int e) { return names[e]; }
}

