// automatically generated by the FlatBuffers compiler, do not modify

package rs.high.life.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AvatarLeftEvent extends Table {
  public static AvatarLeftEvent getRootAsAvatarLeftEvent(ByteBuffer _bb) { return getRootAsAvatarLeftEvent(_bb, new AvatarLeftEvent()); }
  public static AvatarLeftEvent getRootAsAvatarLeftEvent(ByteBuffer _bb, AvatarLeftEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AvatarLeftEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String userId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createAvatarLeftEvent(FlatBufferBuilder builder,
      int userIdOffset) {
    builder.startObject(1);
    AvatarLeftEvent.addUserId(builder, userIdOffset);
    return AvatarLeftEvent.endAvatarLeftEvent(builder);
  }

  public static void startAvatarLeftEvent(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(0, userIdOffset, 0); }
  public static int endAvatarLeftEvent(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // userId
    return o;
  }
  public static void finishAvatarLeftEventBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

