// automatically generated by the FlatBuffers compiler, do not modify

package rs.high.life.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AvatarJoinedEvent extends Table {
  public static AvatarJoinedEvent getRootAsAvatarJoinedEvent(ByteBuffer _bb) { return getRootAsAvatarJoinedEvent(_bb, new AvatarJoinedEvent()); }
  public static AvatarJoinedEvent getRootAsAvatarJoinedEvent(ByteBuffer _bb, AvatarJoinedEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AvatarJoinedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public rs.high.life.fbs.Avatar avatar() { return avatar(new rs.high.life.fbs.Avatar()); }
  public rs.high.life.fbs.Avatar avatar(rs.high.life.fbs.Avatar obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createAvatarJoinedEvent(FlatBufferBuilder builder,
      int avatarOffset) {
    builder.startObject(1);
    AvatarJoinedEvent.addAvatar(builder, avatarOffset);
    return AvatarJoinedEvent.endAvatarJoinedEvent(builder);
  }

  public static void startAvatarJoinedEvent(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addAvatar(FlatBufferBuilder builder, int avatarOffset) { builder.addOffset(0, avatarOffset, 0); }
  public static int endAvatarJoinedEvent(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // avatar
    return o;
  }
  public static void finishAvatarJoinedEventBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

