// automatically generated by the FlatBuffers compiler, do not modify

package rs.high.life.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Avatar extends Table {
  public static Avatar getRootAsAvatar(ByteBuffer _bb) { return getRootAsAvatar(_bb, new Avatar()); }
  public static Avatar getRootAsAvatar(ByteBuffer _bb, Avatar obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Avatar __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String userId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String username() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer usernameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createAvatar(FlatBufferBuilder builder,
      int userIdOffset,
      int usernameOffset) {
    builder.startObject(2);
    Avatar.addUsername(builder, usernameOffset);
    Avatar.addUserId(builder, userIdOffset);
    return Avatar.endAvatar(builder);
  }

  public static void startAvatar(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(0, userIdOffset, 0); }
  public static void addUsername(FlatBufferBuilder builder, int usernameOffset) { builder.addOffset(1, usernameOffset, 0); }
  public static int endAvatar(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // userId
    builder.required(o, 6);  // username
    return o;
  }
  public static void finishAvatarBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

