// automatically generated by the FlatBuffers compiler, do not modify

package rs.high.life.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ConnectRoomRequest extends Table {
  public static ConnectRoomRequest getRootAsConnectRoomRequest(ByteBuffer _bb) { return getRootAsConnectRoomRequest(_bb, new ConnectRoomRequest()); }
  public static ConnectRoomRequest getRootAsConnectRoomRequest(ByteBuffer _bb, ConnectRoomRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ConnectRoomRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String roomId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String userId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String username() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer usernameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createConnectRoomRequest(FlatBufferBuilder builder,
      int roomIdOffset,
      int userIdOffset,
      int usernameOffset) {
    builder.startObject(3);
    ConnectRoomRequest.addUsername(builder, usernameOffset);
    ConnectRoomRequest.addUserId(builder, userIdOffset);
    ConnectRoomRequest.addRoomId(builder, roomIdOffset);
    return ConnectRoomRequest.endConnectRoomRequest(builder);
  }

  public static void startConnectRoomRequest(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(0, roomIdOffset, 0); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(1, userIdOffset, 0); }
  public static void addUsername(FlatBufferBuilder builder, int usernameOffset) { builder.addOffset(2, usernameOffset, 0); }
  public static int endConnectRoomRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // roomId
    builder.required(o, 6);  // userId
    builder.required(o, 8);  // username
    return o;
  }
  public static void finishConnectRoomRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

