// automatically generated by the FlatBuffers compiler, do not modify

package rs.high.life.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class HRRoot extends Table {
  public static HRRoot getRootAsHRRoot(ByteBuffer _bb) { return getRootAsHRRoot(_bb, new HRRoot()); }
  public static HRRoot getRootAsHRRoot(ByteBuffer _bb, HRRoot obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public HRRoot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startHRRoot(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endHRRoot(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishHRRootBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

