# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class AnyServerContent(object):
    NONE = 0
    ConnectRoomResponse = 1
    AvatarJoinedEvent = 2
    AvatarLeftEvent = 3
    VWChatEvent = 4

