# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class AvatarJoinedEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAvatarJoinedEvent(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AvatarJoinedEvent()
        x.Init(buf, n + offset)
        return x

    # AvatarJoinedEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AvatarJoinedEvent
    def Avatar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Avatar import Avatar
            obj = Avatar()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AvatarJoinedEventStart(builder): builder.StartObject(1)
def AvatarJoinedEventAddAvatar(builder, avatar): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(avatar), 0)
def AvatarJoinedEventEnd(builder): return builder.EndObject()
