# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class ConnectRoomResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsConnectRoomResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConnectRoomResponse()
        x.Init(buf, n + offset)
        return x

    # ConnectRoomResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConnectRoomResponse
    def RoomId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def ConnectRoomResponseStart(builder): builder.StartObject(1)
def ConnectRoomResponseAddRoomId(builder, roomId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(roomId), 0)
def ConnectRoomResponseEnd(builder): return builder.EndObject()
