# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class HRRoot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHRRoot(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HRRoot()
        x.Init(buf, n + offset)
        return x

    # HRRoot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def HRRootStart(builder): builder.StartObject(0)
def HRRootEnd(builder): return builder.EndObject()
